### ISSUE TITLE
Helm manifests vs. repo manifests

### ISSUE THREAD

**Issue by technosophos** [deis/charts#19]
Right now, each repo has its own "generic" manifests, while the Helm repo has "standard" manifests.

The goal of the Helm repo is to make it really easy to install, so we want those manifests to work cooperatively.

What should be rules be for "standard" manifests, though? Completely stand-alone? Sorta Deis aware?

**Comment by technosophos** [comment]
@krancour I think you had some thoughts on this.

**Comment by krancour** [comment]
Apologies in advance for the length.  My thoughts:

We obviously _do_ want to keep components as loosely coupled to one another as possible and as reusable as possible, and that probably means limiting awareness of the rest of Deis in each component's repo-- including each repo's `/manifests` dir.  This would be strong impetus to _not_ use the `deis` namespace (for instance) in an individual component repo's `/manifests`.  (Contrast this to the Deis chart, which _should_ provide Deis flavoring.)

This being said... I think it's inevitable that someone (even ourselves) hacking on component `deis/x` will want to test their changes to that component in the context of the rest of Deis.

In v1.x, what is generally done is that people hacking on a particular component start with a _stock_ install of Deis and "side load" their hacked-upon component into their development cluster using `make -C <component> deploy`.  Most of us seem to be honoring a similar workflow in v2-- we begin with a _stock_ install of `v2-alpha` via `helm install deis`.  (This chart!)

So the question is...

Whether officially or unofficially, the jumping off point for someone hacking on a Deis v2 component and wishing to test in the context of the rest of Deis is a _stock_ install via helm _and_ that stock install is fully Deis-flavored (for instance, uses `deis` namespace and `deis` k8s service account), then how can we "side load" hacked components into such a cluster _without_ having each component repo's `/manifests` also be Deis-flavored.  i.e. How can we possibly keep those generic, while still allowing the hacked components to be drop-in replacements for stock components?

The answer, of course, is that this isn't possible.  What we need to do instead is build some kind of consensus on how we approach the overall hacking workflow across / among our diverse components.  (Or we can turn to our BDFL to settle this.  Ping @gabrtv.)

My proposal is that the officially supported dev / hacking workflow for _each_ component is this:
1. Components can stand alone, but their manifests _are_ Deis-flavored.  This may imply use of the `deis` namespace and other "top-level" things within that namespace, such as a `deis` service account for the k8s API.  This will ensure hacked components can be drop-in replacements for stock components.  **EDIT:** Components shouldn't be coded such that they _only_ work in the `deis` namespace.  This is only to say `deis` should be the assumed namespace for components in a dev/test cluster.
2. Because we can't take it for granted that the contributor _is_ testing their component in the context of the full Deis platform, we must also not take it for granted that things like the `deis` namespace and `deis` service account exist.  To that end, I believe that for _each_ component, we should document and support two options:
   
   a. BYO "Deis".  The contributor is accountable for ensuring any k8s prerequisites that are normally provided by this chart and required by the component upon which they are hacking are satisfied.  We could actually provide a `make` target that wraps a few `kubectl` commands to facilitate this with minimal friction.
   
   b. Give the option of starting from a full, stock install of Deis-- via helm.

In either case, what I _am_ championing is sufficient parity between the official charts and the manifests in each component's repos such that someone attempting "b." (which is already happening) won't encounter any difficulty while people committed to hacking components in isolation can still do so.

**Comment by arschles** [comment]
:100: on what @krancour said. Very specifically, I'm "side-loading" [`deis/builder`](https://github.com/deis/builder) and finding that I have to change only the following to make the repo manifest work with the helm install:
1. Use my own image instead of the `deisci/` one
2. Use `name:` selectors instead of `app:` selectors

I don't expect the resolution of this issue to cover (1) - that's probably a completely different discussion.

To solve (2), the simple solution seems to be to standardize on a set of selector names (unless we have already and I'm not aware?)

**Comment by technosophos** [comment]
Yes, we should be using `app:`, since that's the convention the community as a whole seems to be adopting.

**Comment by jchauncey** [comment]
Can we close this?
