### ISSUE TITLE
Persistance storage for Deis-Lite

### ISSUE THREAD

**Issue by rimusz** [deis/charts#50]
I would like to cut the Deis Lite (to work on one node k8s ) with persistent storage from host.
manifests (rc) and storage:
- database
  - /var/lib/postgresql/data
- etcd
  - /var/lib/etcd2
- minio
  - ???
- registry
  - /var/lib/registry

Please correct if anything is wrong or add missing folders/manifests

**Comment by krancour** [comment]
Could I propose an alternate name of "micro-deis"?  I don't even know if this is still a thing, but many years ago there was a virtualized, single node distribution of Cloud Foundry called "Micro Cloud Foundry" and for some reason, the "micro" moniker has seemed ever since to be an extremely fitting adjective for any distributed systems that's scaled down to run on one node.  Merely a thought.

**Comment by rimusz** [comment]
@gabrtv @slack  liked Deis Lite name :) up to them if they want to change it, for now I just want to cut the charts for the one node Deis :)

**Comment by krancour** [comment]
Roger that.  Wasn't aware of previous discussion around this.

**Comment by rimusz** [comment]
@krancour no worries man

**Comment by smothiki** [comment]
I guess for minio it's home folder of the container /home/minio.

**Comment by rimusz** [comment]
thanks @smothiki

**Comment by rimusz** [comment]
@smothiki using `/home/minio` as the volume crashes minio

**Comment by slack** [comment]
Make sure you aren't running into permissions problems (https://github.com/kubernetes/kubernetes/issues/2630).
